import React, { useState } from 'react';
import { Card, CardHeader } from './Card.jsx';

function Hi({ c, children }) {
  const cls = c==='bull' ? 'text-bull font-semibold' : c==='bear' ? 'text-bear font-semibold' : 'text-warn font-semibold';
  return <span className={cls}>{children}</span>;
}
function d(v, suffix='') { return v == null ? '—' : `${v}${suffix}`; }
function pct(v) { return v == null ? '—' : `${v>=0?'+':''}${v.toFixed(2)}%`; }

function buildNoteText(assets, sectors, cis) {
  const brent  = assets.brent;
  const usdZar = assets.usdZar;
  const gold   = assets.gold;
  const r2035  = assets.r2035;
  const top40  = sectors.top40;
  const mining = sectors['Gold Miners'];
  const energy = sectors.Energy;
  const now    = new Date();
  const date   = now.toLocaleDateString('en-ZA', { weekday:'long', day:'numeric', month:'long', year:'numeric' });
  const time   = now.toLocaleTimeString('en-ZA', { timeZone:'Africa/Johannesburg', hour:'2-digit', minute:'2-digit' });

  return [
    `▸ JSE CONFLICT WATCH — MORNING NOTE`,
    `${date.toUpperCase()} · ${time} SAST`,
    ``,
    `CONFLICT IMPACT SCORE: ${cis.total} (${cis.regime})`,
    ``,
    `MACRO SNAPSHOT:`,
    `Brent Crude: ${brent?.price?.toFixed(2) ?? '—'}/bbl (${pct(brent?.changePct)})`,
    `USD/ZAR: R${usdZar?.price?.toFixed(3) ?? '—'} (${pct(usdZar?.changePct)})`,
    `Gold: $${gold?.price?.toFixed(0) ?? '—'}/oz (${pct(gold?.changePct)})`,
    `R2035 Bond Yield: ${r2035?.price?.toFixed(3) ?? '—'}% (${pct(r2035?.changePct)})`,
    ``,
    `JSE SECTOR SNAPSHOT:`,
    `Market Avg: ${pct(top40?.chg)}`,
    `Gold Miners: ${pct(mining?.chg)}`,
    `Energy: ${pct(energy?.chg)}`,
    ``,
    `Generated by JSE Conflict Watch · Yahoo Finance + SARB`,
  ].join('\n');
}

export default function MorningNote({ assets, sectors, cis, hasData }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    const text = buildNoteText(assets, sectors, cis);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch { /* clipboard not available */ }
  }

  if (!hasData) {
    return (
      <Card className="h-full">
        <CardHeader title="Auto-Generated Morning Note" badge="AI GENERATED" badgeVariant="live" />
        <div className="flex items-center justify-center h-32 font-mono text-[10px] text-tm text-center">
          Note generated after live data is fetched
        </div>
      </Card>
    );
  }

  const brent  = assets.brent;
  const usdZar = assets.usdZar;
  const gold   = assets.gold;
  const r2035  = assets.r2035;
  const top40  = sectors.top40;
  const mining = sectors['Gold Miners'];
  const energy = sectors.Energy;
  const now    = new Date();
  const date   = now.toLocaleDateString('en-ZA', { weekday:'long', day:'numeric', month:'long', year:'numeric' });
  const time   = now.toLocaleTimeString('en-ZA', { timeZone:'Africa/Johannesburg', hour:'2-digit', minute:'2-digit' });

  return (
    <Card className="h-full">
      <div className="flex items-center justify-between mb-3">
        <span className="font-mono text-[9px] font-semibold tracking-[2px] text-ts uppercase">Auto-Generated Morning Note</span>
        <div className="flex items-center gap-2">
          <span className="font-mono text-[8px] bg-bull/10 text-bull border border-bull/30 px-1.5 py-0.5 rounded-sm">AI GENERATED</span>
          <button onClick={handleCopy}
            className="flex items-center gap-1 px-2.5 py-1 font-mono text-[9px] border border-bd bg-bg-c rounded hover:text-tp hover:border-ts transition-colors cursor-pointer">
            {copied ? '✓ COPIED' : '📋 COPY'}
          </button>
        </div>
      </div>

      <div className="font-mono text-[10.5px] leading-[1.9] text-ts space-y-2.5">
        <div className="text-warn font-semibold tracking-[0.5px] block">
          ▸ MORNING NOTE · {date.toUpperCase()} · {time} SAST
        </div>
        <p>
          Global markets are pricing Iran–Israel conflict risk near the Strait of Hormuz.{' '}
          <Hi c="warn">Brent {pct(brent?.changePct)} to ${brent?.price?.toFixed(2) ?? '—'}/bbl</Hi>.
          {(brent?.changePct ?? 0) > 4 ? ' RED oil shock threshold breached.' : ' Amber oil shock threshold triggered.'}
        </p>
        <p>
          <Hi c="bear">JSE market avg {pct(top40?.chg)}</Hi> at the open.{' '}
          <Hi c="warn">USD/ZAR R{usdZar?.price?.toFixed(3) ?? '—'} ({pct(usdZar?.changePct)})</Hi>{' '}
          amplifies import cost pressures.{' '}
          R2035 bond yield at <Hi c={r2035?.changePct > 0 ? 'bear' : 'bull'}>{r2035?.price?.toFixed(3) ?? '—'}%</Hi>
          {r2035?.isProxy ? ' (FRED proxy)' : ' (SARB)'}.
        </p>
        <p>
          Key divergence:{' '}
          <Hi c="bull">gold miners {pct(mining?.chg)}</Hi> and{' '}
          <Hi c="bull">energy basket {pct(energy?.chg)}</Hi>{' '}
          provide a partial offset.
        </p>
        <p>
          CIS: <Hi c="warn">{cis.total}</Hi> — <Hi c="warn">{cis.regime}</Hi>.
          {r2035?.price && ` Watch R2035 at ${r2035.price.toFixed(3)}% — 11.0% is key resistance for bank valuations.`}
        </p>
      </div>
    </Card>
  );
}
